lang: ru-RU
encoding: utf-8
url: https://rbobza.github.io/
theme: jekyll-theme-tactile
title: Это просто эхо 
description: Роман Романа Бобзы

seo_tag:
  image:
    path: /cover.jpg
    height: 1064
    width: 764
