lang: ru-RU
encoding: utf-8
url: https://rbobza.github.io
theme: jekyll-theme-tactile
title: Это просто эхо 
description: Роман Романа Бобзы

plugins:
  - jekyll-seo-tag
  
seo_tag:
  image:
    path: "/cover.jpg"
